
package pl.poznan.put.bsr.bank.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankAccountServiceService", targetNamespace = "http://services.bank.bsr.put.poznan.pl/", wsdlLocation = "http://localhost:8000/bankAccounts?WSDL")
public class BankAccountServiceService
    extends Service
{

    private final static URL BANKACCOUNTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKACCOUNTSERVICESERVICE_EXCEPTION;
    private final static QName BANKACCOUNTSERVICESERVICE_QNAME = new QName("http://services.bank.bsr.put.poznan.pl/", "BankAccountServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/bankAccounts?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKACCOUNTSERVICESERVICE_WSDL_LOCATION = url;
        BANKACCOUNTSERVICESERVICE_EXCEPTION = e;
    }

    public BankAccountServiceService() {
        super(__getWsdlLocation(), BANKACCOUNTSERVICESERVICE_QNAME);
    }

    public BankAccountServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKACCOUNTSERVICESERVICE_QNAME, features);
    }

    public BankAccountServiceService(URL wsdlLocation) {
        super(wsdlLocation, BANKACCOUNTSERVICESERVICE_QNAME);
    }

    public BankAccountServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKACCOUNTSERVICESERVICE_QNAME, features);
    }

    public BankAccountServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAccountServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankAccountService
     */
    @WebEndpoint(name = "BankAccountServicePort")
    public BankAccountService getBankAccountServicePort() {
        return super.getPort(new QName("http://services.bank.bsr.put.poznan.pl/", "BankAccountServicePort"), BankAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankAccountService
     */
    @WebEndpoint(name = "BankAccountServicePort")
    public BankAccountService getBankAccountServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.bank.bsr.put.poznan.pl/", "BankAccountServicePort"), BankAccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKACCOUNTSERVICESERVICE_EXCEPTION!= null) {
            throw BANKACCOUNTSERVICESERVICE_EXCEPTION;
        }
        return BANKACCOUNTSERVICESERVICE_WSDL_LOCATION;
    }

}
